apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product-cont
        image: product-service:latest
        ports:
        - containerPort: 8082
        imagePullPolicy: Never
        env:
          - name: DB_HOST
            value: stylekart-db-svc

