apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user-cont
        image: user-service:latest
        ports:
        - containerPort: 8081
        imagePullPolicy: Never
        env:
          - name: DB_HOST
            value: stylekart-db-svc

